
package com.ajsjee.web.payment.dragonpay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MerchantServiceSoap", targetNamespace = "http://api.dragonpay.ph/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MerchantServiceSoap {


    /**
     * Get list of countries
     * 
     * @return
     *     returns com.devkinectics.dragonpaytest.ArrayOfCountry
     */
    @WebMethod(operationName = "GetCountries", action = "http://api.dragonpay.ph/GetCountries")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetCountriesResponse")
    public ArrayOfCountry getCountries();

    /**
     * Get list of processors
     * 
     * @return
     *     returns com.devkinectics.dragonpaytest.ArrayOfProcessorInfo
     */
    @WebMethod(operationName = "GetProcessors", action = "http://api.dragonpay.ph/GetProcessors")
    @WebResult(name = "GetProcessorsResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetProcessors", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetProcessors")
    @ResponseWrapper(localName = "GetProcessorsResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetProcessorsResponse")
    public ArrayOfProcessorInfo getProcessors();

    /**
     * Get transaction status
     * 
     * @param password
     * @param merchantId
     * @param txnId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTxnStatus", action = "http://api.dragonpay.ph/GetTxnStatus")
    @WebResult(name = "GetTxnStatusResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetTxnStatus", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetTxnStatus")
    @ResponseWrapper(localName = "GetTxnStatusResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetTxnStatusResponse")
    public String getTxnStatus(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "password", targetNamespace = "http://api.dragonpay.ph/")
        String password,
        @WebParam(name = "txnId", targetNamespace = "http://api.dragonpay.ph/")
        String txnId);

    /**
     * Retrieve Dragonpay refno
     * 
     * @param password
     * @param merchantId
     * @param txnId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTxnRefNo", action = "http://api.dragonpay.ph/GetTxnRefNo")
    @WebResult(name = "GetTxnRefNoResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetTxnRefNo", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetTxnRefNo")
    @ResponseWrapper(localName = "GetTxnRefNoResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetTxnRefNoResponse")
    public String getTxnRefNo(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "password", targetNamespace = "http://api.dragonpay.ph/")
        String password,
        @WebParam(name = "txnId", targetNamespace = "http://api.dragonpay.ph/")
        String txnId);

    /**
     * Get transaction token
     * 
     * @param password
     * @param amount
     * @param merchantId
     * @param ccy
     * @param merchantTxnId
     * @param description
     * @param email
     * @param param1
     * @param param2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTxnToken", action = "http://api.dragonpay.ph/GetTxnToken")
    @WebResult(name = "GetTxnTokenResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetTxnToken", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetTxnToken")
    @ResponseWrapper(localName = "GetTxnTokenResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetTxnTokenResponse")
    public String getTxnToken(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "password", targetNamespace = "http://api.dragonpay.ph/")
        String password,
        @WebParam(name = "merchantTxnId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantTxnId,
        @WebParam(name = "amount", targetNamespace = "http://api.dragonpay.ph/")
        double amount,
        @WebParam(name = "ccy", targetNamespace = "http://api.dragonpay.ph/")
        String ccy,
        @WebParam(name = "description", targetNamespace = "http://api.dragonpay.ph/")
        String description,
        @WebParam(name = "email", targetNamespace = "http://api.dragonpay.ph/")
        String email,
        @WebParam(name = "param1", targetNamespace = "http://api.dragonpay.ph/")
        String param1,
        @WebParam(name = "param2", targetNamespace = "http://api.dragonpay.ph/")
        String param2);

    /**
     * Void transaction
     * 
     * @param password
     * @param merchantId
     * @param merchantTxnId
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CancelTransaction", action = "http://api.dragonpay.ph/CancelTransaction")
    @WebResult(name = "CancelTransactionResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "CancelTransaction", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.CancelTransaction")
    @ResponseWrapper(localName = "CancelTransactionResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.CancelTransactionResponse")
    public int cancelTransaction(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "password", targetNamespace = "http://api.dragonpay.ph/")
        String password,
        @WebParam(name = "merchantTxnId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantTxnId);

    /**
     * Send Billing Info via SOAP
     * 
     * @param firstName
     * @param lastName
     * @param country
     * @param zipCode
     * @param merchantId
     * @param address2
     * @param city
     * @param address1
     * @param merchantTxnId
     * @param state
     * @param telNo
     * @param email
     * @return
     *     returns int
     */
    @WebMethod(operationName = "SendBillingInfo", action = "http://api.dragonpay.ph/SendBillingInfo")
    @WebResult(name = "SendBillingInfoResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "SendBillingInfo", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.SendBillingInfo")
    @ResponseWrapper(localName = "SendBillingInfoResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.SendBillingInfoResponse")
    public int sendBillingInfo(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "merchantTxnId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantTxnId,
        @WebParam(name = "firstName", targetNamespace = "http://api.dragonpay.ph/")
        String firstName,
        @WebParam(name = "lastName", targetNamespace = "http://api.dragonpay.ph/")
        String lastName,
        @WebParam(name = "address1", targetNamespace = "http://api.dragonpay.ph/")
        String address1,
        @WebParam(name = "address2", targetNamespace = "http://api.dragonpay.ph/")
        String address2,
        @WebParam(name = "city", targetNamespace = "http://api.dragonpay.ph/")
        String city,
        @WebParam(name = "state", targetNamespace = "http://api.dragonpay.ph/")
        String state,
        @WebParam(name = "country", targetNamespace = "http://api.dragonpay.ph/")
        String country,
        @WebParam(name = "zipCode", targetNamespace = "http://api.dragonpay.ph/")
        String zipCode,
        @WebParam(name = "telNo", targetNamespace = "http://api.dragonpay.ph/")
        String telNo,
        @WebParam(name = "email", targetNamespace = "http://api.dragonpay.ph/")
        String email);

    /**
     * Get all txns for a date range for a particular merchant
     * 
     * @param password
     * @param dStart
     * @param merchantId
     * @param dEnd
     * @return
     *     returns com.devkinectics.dragonpaytest.ArrayOfTransaction
     */
    @WebMethod(operationName = "GetMerchantTxns", action = "http://api.dragonpay.ph/GetMerchantTxns")
    @WebResult(name = "GetMerchantTxnsResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetMerchantTxns", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetMerchantTxns")
    @ResponseWrapper(localName = "GetMerchantTxnsResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetMerchantTxnsResponse")
    public ArrayOfTransaction getMerchantTxns(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "password", targetNamespace = "http://api.dragonpay.ph/")
        String password,
        @WebParam(name = "dStart", targetNamespace = "http://api.dragonpay.ph/")
        XMLGregorianCalendar dStart,
        @WebParam(name = "dEnd", targetNamespace = "http://api.dragonpay.ph/")
        XMLGregorianCalendar dEnd);

    /**
     * Get all settled txns for a date range for a particular merchant
     * 
     * @param password
     * @param dStart
     * @param merchantId
     * @param dEnd
     * @return
     *     returns com.devkinectics.dragonpaytest.ArrayOfTransaction
     */
    @WebMethod(operationName = "GetMerchantSettledTxns", action = "http://api.dragonpay.ph/GetMerchantSettledTxns")
    @WebResult(name = "GetMerchantSettledTxnsResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetMerchantSettledTxns", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetMerchantSettledTxns")
    @ResponseWrapper(localName = "GetMerchantSettledTxnsResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetMerchantSettledTxnsResponse")
    public ArrayOfTransaction getMerchantSettledTxns(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "password", targetNamespace = "http://api.dragonpay.ph/")
        String password,
        @WebParam(name = "dStart", targetNamespace = "http://api.dragonpay.ph/")
        XMLGregorianCalendar dStart,
        @WebParam(name = "dEnd", targetNamespace = "http://api.dragonpay.ph/")
        XMLGregorianCalendar dEnd);

    /**
     * Get switch log details for a particular refno
     * 
     * @param refNo
     * @param password
     * @param merchantId
     * @return
     *     returns com.devkinectics.dragonpaytest.ArrayOfTransactionLog
     */
    @WebMethod(operationName = "GetSwitchTxnLogs", action = "http://api.dragonpay.ph/GetSwitchTxnLogs")
    @WebResult(name = "GetSwitchTxnLogsResult", targetNamespace = "http://api.dragonpay.ph/")
    @RequestWrapper(localName = "GetSwitchTxnLogs", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetSwitchTxnLogs")
    @ResponseWrapper(localName = "GetSwitchTxnLogsResponse", targetNamespace = "http://api.dragonpay.ph/", className = "com.devkinectics.dragonpaytest.GetSwitchTxnLogsResponse")
    public ArrayOfTransactionLog getSwitchTxnLogs(
        @WebParam(name = "merchantId", targetNamespace = "http://api.dragonpay.ph/")
        String merchantId,
        @WebParam(name = "password", targetNamespace = "http://api.dragonpay.ph/")
        String password,
        @WebParam(name = "refNo", targetNamespace = "http://api.dragonpay.ph/")
        String refNo);

}
